version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: epitanie
      POSTGRES_PASSWORD: epitanie
      POSTGRES_DB: epitanie
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  pgdata:
